# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shop101' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage/WebP'


  # Pods for Shop101

  target 'Shop101Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
